### PR TITLE
week6 part6 homework

### PR DESCRIPTION
**Pull request by Yo7ee**
hi 彭彭老師
宥琪
http://3.224.188.5:3000/

### CODE REVIEW

**Comment by cwpeng** [comment]
Remove booking data after successful ordering.

**Comment by Yo7ee** [comment]
Done for removing booking data

**Comment by cwpeng** [comment]
I can approve your pull request only if you request me review.

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Comment by Yo7ee** [comment]
Hi 彭彭老師
忘記把上週的pull request merge.....

這週修改內容：
1. homePage的loading效果
2. 註冊帳號時，前端驗證email格式
3. 新增會員中心頁面，尚未有修改密碼功能
4. 點擊訂單編號，查詢訂單詳細資訊

宥琪
http://3.224.188.5:3000/

**Review by cwpeng — APPROVED** [review]
Good jobs. Don't hesitate to make your next project as soon as possible. :)

We should remove redundant console.log() in code after everything is OK.

**Pull request merged**
