### PR TITLE
week3 part3

### PR DESCRIPTION
**Pull request by Yo7ee**
宥琪
http://3.224.188.5:3000/attraction/
http://3.224.188.5:3000/attraction/10
圖片輪播是當選擇下一張時，才讀取該張圖片，網路較慢會影響使用者體驗，不確定這個方法可不可行。

### CODE REVIEW

**Comment by cwpeng** [comment]
1. Homepage in tablet size is too bad to be accepted.
2. Line height in order box is too large. Text size of attraction information is too large.
3. Aspect ratio (長寬比) of images is broken in small and middle size devices.

未命名-9
未命名-10

**Comment by Yo7ee** [comment]
Hi 彭彭老師
I've fix three issues so far, please help to check again, thank you.

**Comment by cwpeng** [comment]
1. OK.
2. OK.
3. No fix.

未命名-2

**Comment by Yo7ee** [comment]
Hi 彭彭老師
I've fixed the issue, please help to check again, thank you.

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
