### PR TITLE
Level2 week1 homework

### PR DESCRIPTION
**Pull request by Yo7ee**
宥琪
http://3.224.188.5:3000/api/attractions?page=3
http://3.224.188.5:3000/api/attractions?page=3&keyword=北投
http://3.224.188.5:3000/api/attraction/4

### CODE REVIEW

**Comment by cwpeng** [comment]
"nextPage" field in http://3.224.188.5:3000/api/attractions/?page=4 and http://3.224.188.5:3000/api/attractions/?page=0&keyword=%E9%A4%A8 are not in the correct position. Check response structure in API spec carefully.

Fix issue and leave comment for me to review again.

**Comment by Yo7ee** [comment]
Hi teacher
I've fix the nextpage issue by adding one more if/else. Please help to check again, thank you.

**Comment by cwpeng** [comment]
"nextPage" field not in "data" field. It's in the same level as "data" field. There is only one "nextPage" field in a response.

Fix it and leave comment for me to review again.

**Comment by Yo7ee** [comment]
Fixed the nextPage only in one dict.

**Comment by cwpeng** [comment]
Obviously incorrect. Check API response format carefully.

**Comment by Yo7ee** [comment]
Fix nextPage and data which in incorrect object and array

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
